### ISSUE TITLE
npm ERR! code EJSONPARSE

### ISSUE THREAD

**Issue by Paulius11** [Paulius11/Takas#21]
https://github.com/Paulius11/Takas/blob/067b356186e4303c94e1e3e5f378cdfd776cf826/frontend/package.json#L8

@iamEJ  kai meginu paleisti, `npm start` rodo `npm ERR! code EJSONPARSE`

**Comment by iamEJ** [comment]
pakeisk eilutę į  "@material-ui/lab": "^4.0.0-alpha.56", 
matyt ištrinta buvo
